/**
 * Writes fixtures/SYNTHETIC_flipkart_sales_report.xlsx — a clearly labelled
 * synthetic workbook for trying the importer. It is NOT real Flipkart data.
 */
import { writeFileSync } from 'node:fs';
import * as XLSX from 'xlsx';
import { FLIPKART_SHEET_NAME } from '../src/schemas/flipkart';
import { demoRows, toAoa } from '../src/tests/fixtures/synthetic';

const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(
  wb,
  XLSX.utils.aoa_to_sheet([
    ['SYNTHETIC TEST DATA — NOT A REAL FLIPKART REPORT'],
    ['Generated by scripts/make-fixture.ts for testing the importer.'],
    ['Event values and the negative-return sign convention in this file are assumptions, not verified Flipkart behaviour.'],
  ]),
  'READ ME - synthetic',
);
const ws = XLSX.utils.aoa_to_sheet(toAoa(demoRows()));
XLSX.utils.book_append_sheet(wb, ws, FLIPKART_SHEET_NAME);
const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx', compression: true }) as Buffer;
writeFileSync('fixtures/SYNTHETIC_flipkart_sales_report.xlsx', buf);
console.log(`Wrote fixtures/SYNTHETIC_flipkart_sales_report.xlsx (${demoRows().length} data rows)`);
